sia20:
    # Publish all joint state ---------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    # Position Controllers ------------------------------
    sia20_arm_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            joints:
                - joint_s
                - joint_l
                - joint_e
                - joint_u
                - joint_r
                - joint_b
                - joint_t
