sia20:
    # Publish all joint state ---------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    # Position Controllers ------------------------------
    sia20_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - joint_s
            - joint_l
            - joint_e
            - joint_u
            - joint_r
            - joint_b
            - joint_t

        gains:
            joint_s: {p: 1000, i: 800, d: 200}
            joint_l: {p: 1000, i: 800, d: 200}
            joint_e: {p: 1000, i: 800, d: 200}
            joint_u: {p: 1000, i: 800, d: 200}
            joint_r: {p: 1000, i: 800, d: 200}
            joint_b: {p: 1000, i: 800, d: 200}
            joint_t: {p: 1000, i: 800, d: 200}

