controller_list:
    - name: /sia20/sia20_joint_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - joint_s
          - joint_l
          - joint_e
          - joint_u
          - joint_r
          - joint_b
          - joint_t
    - name: hand_controller
      action_ns: gripper_action
      type: GripperCommand
      default: true
      paralell: true
      joints:
          - wrist_to_l
          - wrist_to_r

