controller_list:
  - name: fake_sia20_arm_controller
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t
  - name: fake_sia20_gripper_controller
    joints:
      - wrist_to_l
      - wrist_to_r